version: '3'
services:
  postgresql:
      container_name: postgresql
      build: ./postgres
      ports:
        - 5432:5432
      volumes:
        - ./postgres/data:/var/lib/postgresql/data
        - ./postgres/init:/docker-entrypoint-initdb.d
      environment:
        POSTGRES_USER: root
        POSTGRES_PASSWORD: root
        POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
        TZ: "Asia/Tokyo"
      hostname: postgres
      restart: always
      user: root

  pgadmin4:
    container_name: pgadmin4
    image: dpage/pgadmin4:3.3
    ports:
      - 12000:80
    volumes:
      - ./pgadmin:/var/lib/pgadmin/storage
    environment:
      PGADMIN_DEFAULT_EMAIL: root
      PGADMIN_DEFAULT_PASSWORD: root
    hostname: pgadmin4
    restart: always
